### ISSUE TITLE
Feature Request: Strip Comments of Whitespaces

### ISSUE THREAD

**Issue by whinee** [bricesuazo/cvsu.me#110] opened 2024-09-15 14:45 UTC
## Feature Request

title.

## Rationale

Users often times type "return" or "enter" in their keyboard to send their comment to the post. but in this website, it doesnt do that, and instead makes a new line. sometimes, users does not delete this newly created line and just press the "comment" button immediately. this in turn leads to an ugly space in between the comment and its interaction elements.  

![Screenshot 2024-09-15 at 22-34-44 nya - @johnalbert-balani - Kabsu me](https://github.com/user-attachments/assets/8177c0fd-9850-4e3f-a281-871078cfd007)

**Comment by waffensultan** [comment] 2024-09-16 03:54
Can't reproduce this on my side. It seems that the form submission handler already trims posts of trailing whitespaces.

![image](https://github.com/user-attachments/assets/d9b53e64-6836-4003-b179-74c353ee2398)

**Comment by whinee** [comment] 2024-09-16 04:36
thats weird huhuu

**Comment by bricesuazo** [comment] 2024-09-16 09:36
Yep, also getting the same issue.

![image](https://github.com/user-attachments/assets/394d3e4c-9c7e-46c6-b67c-ccc4eb9ff0f0)

**Comment by waffensultan** [comment] 2024-09-16 09:39
Oh, it's the comments that are showing this behaviour. My mistake @whinee 

This seems to be an interesting issue to look into

**Comment by waffensultan** [comment] 2024-09-16 10:00
I think I've found a fix for this. Can this be assigned to me? @bricesuazo

**Comment by bricesuazo** [comment] 2024-09-16 10:01
> I think I've found a fix for this. Can this be assigned to me? @bricesuazo

Sure.

**Comment by waffensultan** [comment] 2024-09-16 10:10
I've submitted a PR for the possible fix. Thank you! @bricesuazo

**Closed as completed** 2024-09-17 16:02 UTC
Labels: bug
